
// This file simulates the TypeScript code that would be generated by `protoc`
// It maps the Proto definitions to TS Interfaces

// --- USER ---
export interface UserProfile {
  id: string;
  displayName: string;
  avatarUrl: string;
  frameUrl?: string;
  goldBalance: number;
  level: number;
  isVerified: boolean;
  privacy: {
    showSocialList: boolean;
    showOnlineStatus: boolean;
  };
  rank?: {
    rankName: string;
    colorHex: string;
  };
}

// --- ECONOMY ---
export interface GiftItem {
  id: string;
  name: string;
  iconChar: string;
  cost: number;
}

// --- ROOM ---
export interface RoomSeat {
  index: number;
  userId?: string;
  user?: UserProfile;
  isMuted: boolean;
  isLocked: boolean;
}

export interface Room {
  id: string;
  title: string;
  description?: string;
  countryFlag: string;
  tags: string[];
  host: UserProfile;
  seats: RoomSeat[];
  onlineCount: number;
}

// --- CHAT ---
export enum MessageType {
  TEXT = 'text',
  GIFT = 'gift',
  SYSTEM = 'system',
}

export interface Message {
  id: string;
  senderId: string;
  senderName: string; // Flattened for convenience in UI
  content: string;
  timestamp: string; // Using string for ISO dates in TS
  type: MessageType;
  giftData?: GiftItem;
  reactions?: Record<string, number>;
}

export interface ChatContact {
  id: string;
  user: UserProfile;
  lastMessage: string;
  time: string;
}

// --- SOCIAL 3D ---
export interface SocialNode {
  user: UserProfile;
  x: number;
  y: number;
  z: number;
  connectionIds: string[];
  commonInterests: string[];
}
