syntax = "proto3";

package messages;

import "models/user.proto";
import "models/common.proto";

option go_package = "middle-east-im-server/pkg/pb/messages";

// 更新资料请求
message UpdateProfileRequest {
  string display_name = 1;
  string avatar_url = 2;
  string frame_url = 3;
  string rank_name = 4;
}

// 搜索用户请求
message SearchUsersRequest {
  string query = 1;
  int32 page = 2;
  int32 limit = 3;
}

// 搜索用户响应
message SearchUsersResponse {
  models.Response response = 1;
  repeated models.User list = 2;
  int64 total = 3;
}
